language: java
jdk: [openjdk8]
dist: xenial
os: linux
install: skip
addons:
  sonarcloud:
    organization: "lorenzo0111"
    token:
      secure: "i3pQxR3bVarM+b2qd8+x4SShAssLXSi/DWFnraxaAVJdQrc1ubGDbEBr7qsIDh8UGg5svWTeAIrPs9P/jLijhDpLn2keAM4WPnVH7Qe8nkOQunAnP7ZP8CDraphU0XDqGJvdKi5uUOycexUT4cZuE8+yzewrmMPbk6b8ZDA5kxGAOFHsugLtd7Ob68J5mG3chrixfzFUcZ2Owd24E10QDBQptE27V/dSVEhwk56ac7Fvh2QZKVTHsws7aXVzHXSc0Zrh3DP5a6r+/DgN3YTCm8mW/bx0L+pa7VOVq4zkS8OYIGSsPoKzsm3P7NDpOZDarvH7QBEYmRR/z0fyHWywSJGgEio1orrM8yRMMwnyQoMZIKpDmodJs+5f54yr3RfN0feSHwQQbtNBtGAz8qLE/J0zr4lqQbiRSX7KC69vdspvIIdoyFL37rgXVKBquE6weEs1RfZI4WXqMZQgEgQ7Gv+QuATPgrtAJEWKBRdlViVK+dnXlz37yD9UxYQPKcXVMmqlg++wm5BLzIuzdjyw3SiRBxYLN7Ff+SCrjvC9zKBFW0fbCY01OZoCYPFGUqownEHCyL2POjyHyWFzLPqw/n2C3ArD8qIPZgNbxjayrq3UHXHjBx2jSyD1/vvrcXZgZXcTQfWy8LSNXX0fsYA/Wpa/kF3SZ6QfABquBGf9KA8="
script:
  - ./gradlew sonarqube shadowJar
